packaging_format = 2

id = "firefish"
name = "Firefish"
description.en = "Fork of Misskey with better UI/UX, security, features"
description.fr = "Un fork de Misskey avec une meilleure interface utilisateur, la sécurité, les fonctionnalités"

version = "20240330~ynh1"

maintainers = ["oufmilo"]

[upstream]
license = "AGPL-3.0"
website = "https://joinfirefish.org/"
demo = "https://joinfirefish.org/"
code = "https://firefish.dev/firefish/firefish"

[integration]
yunohost = ">= 11.1.14"
architectures = "all"
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"
disk = "50M"
ram.build = "2G"
ram.runtime = "2G"

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "domain"

    [install.init_main_permission]
    help.en = "If enabled, Firefish will be accessible by people who do not have an account. This can be changed later via the webadmin."
    help.fr = "Si cette case est cochée, Firefish sera accessible aux personnes n’ayant pas de compte. Vous pourrez changer ceci plus tard via la webadmin."
    type = "group"
    default = "visitors"

[resources]

    [resources.sources.main]
    url = "https://firefish.dev/firefish/firefish/-/archive/v20240330/firefish-v20240330.tar.gz"
    sha256 = "ddd60ffd9d8157a7f65d502910e4c0d6f25095ce9f816b1acc5233c3feedec4d"
    autoupdate.strategy = "latest_gitlab_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 3020

    [resources.apt]
    packages = "ffmpeg, postgresql, build-essential"

    [resources.database]
    type = "postgresql"
